### ISSUE TITLE
?? What is this packge?

### ISSUE THREAD

**Issue by giangdinh** [rosineygp/PyIsEven#8]

**Comment by beautah** [comment]
The premier python package for checking the even-ness of a number via a microservice/API. Built-ins are overrated, microservices are always best, regardless of scope. I read it in a medium article, so...

**Comment by rosineygp** [comment]
Solve 'is even' is a very complex problem... so use an API is the best way to keep your effort at the business rules.

This package only remove the complexity to interactive with the API

**Comment by giangdinh** [comment]
Closed!
